spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.0.111:1433;DatabaseName=spaceCodeDB
    username: sa
    password: 123456
  freemarker:
    ache: false
    settings:
      template_update_delay: 0
    suffix: .ftl
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true # 确认消息已发送到队列(Queue)
    template:
      mandatory: true  # 只要抵达队列，就会优先异步调用returnconfirm方法


mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    name: logs/space.log
